name: build-release
on: [push]
jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install build-essential libpugixml-dev libcurl4-openssl-dev libsystemd-dev meson valac libsoup-3.0-dev
      - run: sudo apt-get -y install gobject-introspection libgirepository1.0-dev
      - run: cd /home/runner/work
      - run: wget https://github.com/GNOME/gssdp/archive/refs/tags/gssdp-1.6.2.tar.gz -O /home/runner/work/gssdp-1.6.2.tar.gz
      - run: cd /home/runner/work && tar xvf gssdp-1.6.2.tar.gz
      - run: cd /home/runner/work/gssdp-gssdp-1.6.2 && mkdir build
      - run: cd /home/runner/work/gssdp-gssdp-1.6.2/build && meson .. && sudo meson install
      - run: cd /home/runner/work/ssdp-advertiser/ssdp-advertiser
      - run: ./autogen.sh
      - run: ./configure --prefix=/usr
      - run: make
